import json
import logging
from enum import Enum
from typing import Dict, Any, List, Optional
from pydantic import BaseModel, Field

from equimind.providers.base import LLMProvider, LLMMessage, Role

logger = logging.getLogger(__name__)


class SectorType(str, Enum):
    SEMICONDUCTOR_TECH = "semiconductor_tech"
    BANKING_FINANCE = "banking_finance"
    PHARMA_HEALTHCARE = "pharma_healthcare"
    AIRLINE_TRANSPORT = "airline_transport"
    ENERGY_COMMODITIES = "energy_commodities"
    RETAIL_CONSUMER = "retail_consumer"
    SAAS_SOFTWARE = "saas_software"
    GENERAL_EQUITY = "general_equity"


class InvestmentHorizon(str, Enum):
    DAY_TRADING = "day_trading"
    SHORT_TERM = "short_term"      # < 3 months
    MEDIUM_TERM = "medium_term"    # 3 - 12 months
    LONG_TERM = "long_term"        # > 1 year


class ResearchPlan(BaseModel):
    """Dynamic research execution plan generated by the Reasoning Planner Agent."""
    ticker: str
    company_name: Optional[str] = None
    sector: SectorType = SectorType.GENERAL_EQUITY
    horizon: InvestmentHorizon = InvestmentHorizon.LONG_TERM
    user_intent: str
    active_teams: List[str] = Field(default_factory=lambda: ["market_data", "fundamentals", "macro", "web_intelligence"])
    active_adapters: List[str] = Field(default_factory=lambda: [
        "sec_filings", "financial_news", "reddit", "twitter_x", "earnings_transcripts"
    ])
    skipped_teams_rationale: Dict[str, str] = Field(default_factory=dict)
    focus_areas: List[str] = Field(default_factory=list)


class ReasoningPlanner:
    """Agent responsible for analyzing the investment request and dynamically composing the research DAG."""

    @classmethod
    def plan(
        cls,
        query: str,
        ticker: str,
        provider: Optional[LLMProvider] = None,
        as_of_date: Optional[str] = None,
    ) -> ResearchPlan:
        """Generates a dynamic research plan tailored to the company sector and user query."""
        ticker_upper = ticker.upper().strip()
        sector = cls._detect_sector(ticker_upper, query)
        horizon = cls._detect_horizon(query)

        active_teams = ["market_data", "fundamentals", "macro", "web_intelligence"]
        active_adapters = ["sec_filings", "financial_news", "reddit", "twitter_x", "earnings_transcripts"]
        skipped_rationale: Dict[str, str] = {}
        focus_areas: List[str] = []

        # Customize based on sector rules
        if sector == SectorType.SEMICONDUCTOR_TECH:
            active_adapters.extend(["github_commits", "job_postings"])
            focus_areas = ["Capex & Fab Utilization", "GPU/AI Demand", "R&D Spend", "Developer Adoption"]
        elif sector == SectorType.BANKING_FINANCE:
            focus_areas = ["Net Interest Margin (NIM)", "Tier 1 Capital Ratio", "Non-Performing Assets (NPA)", "Fed Rate Sensitivity"]
            # Skip developer commit monitoring for banks
        elif sector == SectorType.AIRLINE_TRANSPORT:
            focus_areas = ["Jet Fuel Prices (Brent Oil)", "Load Factor", "Passenger Yield", "Debt Load"]
        elif sector == SectorType.SAAS_SOFTWARE:
            active_adapters.extend(["github_commits", "job_postings"])
            focus_areas = ["ARR Growth", "Net Retention Rate (NRR)", "Gross Margin", "CAC Payback"]

        # If LLM provider is present, refine the plan dynamically
        if provider and provider.is_available():
            try:
                system_prompt = (
                    "You are the Lead Reasoning Planner Agent at an institutional Equity Research firm. "
                    "Analyze the user's research request and return a JSON object classifying sector, "
                    "focus areas, active adapters, and skipped teams."
                )
                prompt = (
                    f"Ticker: {ticker_upper}\nQuery: '{query}'\nDetected Sector: {sector.value}\n"
                    "Output JSON schema:\n"
                    "{\n"
                    '  "sector": "semiconductor_tech" | "banking_finance" | "saas_software" | "general_equity",\n'
                    '  "focus_areas": ["area1", "area2"],\n'
                    '  "active_adapters": ["sec_filings", "financial_news", "reddit", "twitter_x", "github_commits"]\n'
                    "}"
                )
                resp = provider.generate(
                    messages=[
                        LLMMessage(role=Role.SYSTEM, content=system_prompt),
                        LLMMessage(role=Role.USER, content=prompt),
                    ],
                    temperature=0.1,
                )
                if resp.content:
                    parsed = json.loads(resp.content.strip().strip("```json").strip("```"))
                    if "focus_areas" in parsed and isinstance(parsed["focus_areas"], list):
                        focus_areas = parsed["focus_areas"]
                    if "active_adapters" in parsed and isinstance(parsed["active_adapters"], list):
                        active_adapters = parsed["active_adapters"]
            except Exception as e:
                logger.warning(f"LLM planner refinement skipped due to error: {e}. Using deterministic plan.")

        return ResearchPlan(
            ticker=ticker_upper,
            company_name=ticker_upper,
            sector=sector,
            horizon=horizon,
            user_intent=query,
            active_teams=active_teams,
            active_adapters=list(set(active_adapters)),
            skipped_teams_rationale=skipped_rationale,
            focus_areas=focus_areas,
        )

    @staticmethod
    def _detect_sector(ticker: str, query: str) -> SectorType:
        q_lower = query.lower()
        t_upper = ticker.upper()

        semi_tickers = {"NVDA", "AMD", "INTC", "TSM", "AVGO", "MU", "ARM", "QCOM"}
        bank_tickers = {"JPM", "BAC", "C", "WFC", "GS", "MS", "HDFCBANK", "ICICIBANK"}
        airline_tickers = {"DAL", "UAL", "AAL", "LUV", "INDIGO"}
        saas_tickers = {"CRM", "SNOW", "PLTR", "NOW", "DDOG"}

        if t_upper in semi_tickers or any(w in q_lower for w in ["gpu", "chip", "semiconductor", "fab"]):
            return SectorType.SEMICONDUCTOR_TECH
        elif t_upper in bank_tickers or any(w in q_lower for w in ["bank", "nim", "npa", "loan"]):
            return SectorType.BANKING_FINANCE
        elif t_upper in airline_tickers or any(w in q_lower for w in ["airline", "flight", "passenger"]):
            return SectorType.AIRLINE_TRANSPORT
        elif t_upper in saas_tickers or any(w in q_lower for w in ["saas", "arr", "cloud", "recurring"]):
            return SectorType.SAAS_SOFTWARE
        else:
            return SectorType.GENERAL_EQUITY

    @staticmethod
    def _detect_horizon(query: str) -> InvestmentHorizon:
        q_lower = query.lower()
        if any(w in q_lower for w in ["today", "intraday", "day trade"]):
            return InvestmentHorizon.DAY_TRADING
        elif any(w in q_lower for w in ["swing", "next month", "short term"]):
            return InvestmentHorizon.SHORT_TERM
        elif any(w in q_lower for w in ["long term", "5 years", "10 years", "buy and hold"]):
            return InvestmentHorizon.LONG_TERM
        else:
            return InvestmentHorizon.MEDIUM_TERM
